services:
  backend:
    build:
      context: ./backend
      dockerfile: Backend.dockerfile

    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

  frontend:
    build:
      context: ./frontend
      dockerfile: Frontend.dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend