spring:
  application:
    name: ApiGateway
  rabbitmq:
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASSWORD:guest}
    host: ${RABBIT_SERVICE:localhost}
    port: ${RABBIT_PORT:5672}

server:
  port: 8080

rabbitmq:
  scanner:
    queue:
      name: scanner_queue
  response:
    queue:
      name: result_queue