spring:
  application:
    name: Scanner
  profiles:
    active: ${ACTIVE_PROFILE:prod}
  rabbitmq:
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASSWORD:guest}
    host: ${RABBIT_SERVICE:localhost}
    port: ${RABBIT_PORT:5672}

server:
  port: 8081

rabbitmq:
  request:
    queue:
      name: scanner_queue
  response:
    success:
      queue:
        name: parser_queue
    error:
      queue:
        name: result_queue