spring:
  application:
    name: CodeGenerator
  profiles:
    active: ${ACTIVE_PROFILE:prod}
  rabbitmq:
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASSWORD:guest}
    host: ${RABBIT_SERVICE:localhost}
    port: ${RABBIT_PORT:5672}

server:
  port: 8084

rabbitmq:
  request:
    queue:
      name: code_generator_queue
  response:
    queue:
      name: result_queue