spring:
  application:
    name: ApiGateway
  rabbitmq:
    username: guest
    password: guest
    host: localhost
    port: 5672

server:
  port: 8085

rabbitmq:
  request:
    queue:
      name: code_generator_queue
  response:
    queue:
      name: result_queue