spring:
  application:
    name: IRGenerator
  profiles:
    active: ${ACTIVE_PROFILE:prod}
  rabbitmq:
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASSWORD:guest}
    host: ${RABBIT_SERVICE:localhost}
    port: ${RABBIT_PORT:5672}

server:
  port: 8083

rabbitmq:
  request:
    queue:
      name: ir_generator_queue
  response:
    success:
      queue:
        name: code_generator_queue
    error:
      queue:
        name: result_queue